// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// desCpp
bool desCpp(List transitions, IntegerMatrix transmat);
RcppExport SEXP despackage_desCpp(SEXP transitionsSEXP, SEXP transmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type transmat(transmatSEXP);
    rcpp_result_gen = Rcpp::wrap(desCpp(transitions, transmat));
    return rcpp_result_gen;
END_RCPP
}
