library(shiny)
library(DiagrammeR)

shinyUI(fluidPage(
    titlePanel("Discrete Event Simulation"),
    sidebarLayout(
        sidebarPanel(
            conditionalPanel(condition="input.selectedtab==1",
                             h3("Upload data"),
                             HTML("<h4><strong>NB: This step is entirely optional</strong></h4>"),
                             HTML(paste("Upload a CSV file containing patient level data on transition times and attribute values.", 
                                        "If specified, then models of transition times and individual level attributes can be based on this data.", 
                                        "If not provided then these values will have to be completely specified.")),
                             br(),
                             HTML(paste("Please organise the data in long format, similar to that required by the <code>mstate</code> package, with a row per possible transition.",
                                        "Each row should include patient level covariates as well as the standard time and status indicator for that transition.",
                                        "A column indicating the transition each row belongs to would also be very useful")),
                             hr(),
                             fileInput("covarinput", "Select CSV file", 
                                       accept=c('text/csv', 'text/comma-separated-values,text/plain', '.csv')),
                             uiOutput("specifycols")
                             ),
            conditionalPanel(condition="input.selectedtab==2",
                             h3("States"),
                             uiOutput("stateslider"),
                             uiOutput("states"),
                             actionButton("updatestates", "Update"),
                             hr(),
                             h3("Transitions"),
                             uiOutput("newtransheader"),
                             uiOutput("seltrans"),
                             uiOutput("addtransbutton"),
                             uiOutput("currtransheader"),
                             uiOutput("currtrans")
                             ),
            conditionalPanel(condition="input.selectedtab==3",
                             h3("Individual attributes"),
                             HTML(paste("Prior distributions for individual level attributes can be assigned to the simulation, thereby allowing transition probabilities to vary across individuals.",
                                        "These distributions can be obtained from an uploaded CSV file from the previous step, or can be specified below in the <strong>Simulate</strong> section.",
                                        "Mixtures of empirical and simulated prior distributions can be used.")),
                             br(),
                             br(),
                             HTML(paste("Please note that currently only <strong>fixed-time</strong> attributes are permitted.",
                                        "It is for this reason that we allow the subsetting of the uploaded data set to a particular transition.")),
                             br(),
                             hr(),
                             h3("Empirical covariates"),
                             uiOutput("loadattributes"),
                             hr(),
                             h3("Simulated covariates"),
                             uiOutput("simattributes")
                             ),
            conditionalPanel(condition="input.selectedtab==4",
                             h3("Transition Probabilities"),
                             uiOutput("probsheader"),
                             uiOutput("seltransprobs"),
                             uiOutput("transprobsbuttons"),
                             hr(),
                             uiOutput("addtransarea")
                             ),
            conditionalPanel(condition="input.selectedtab==5",
                             h3("Transition time distributions"),
                             uiOutput("newdataarea")
                             ),
            conditionalPanel(condition="input.selectedtab==6",
                             h3("Simulation"),
                             actionButton("runsimbutton", "Run simulation once"),
                             sliderInput("simslider", "Number of simulations", min=10, max=10000, value=1000),
                             actionButton("runmultiplesimbutton", "Run simulation multiple times")
                             ),
            width=3
        ),
        mainPanel(
            tabsetPanel(type="tabs",
                        tabPanel("Upload Data",
                                 h3("Data Peak"),
                                 uiOutput("datatable"),
                                 h3("Attribute information"),
                                 uiOutput("rawattrinfo"),
                                 value=1
                                 ),
                        tabPanel("States",
                                 grVizOutput("statedia"),
                                 value=2),
                        tabPanel("Individual Attributes",
                                 uiOutput("sampledistheader"),
                                 plotOutput("plotarea"),
                                 value=3),
                        tabPanel("Transition Probabilities",
                                 h3("Transition probabilities"),
                                 uiOutput("transprobssummary"),
                                 uiOutput("aicdiv"),
                                 value=4),
                        tabPanel("Event Time Distributions",
                                 h3("Event time distributions"),
                                 plotOutput("plottingeventdraws"),
                                 value=5),
                        tabPanel("Simulation",
                                 h3("Run simulation"),
                                 uiOutput("timedisplay"),
                                 value=6),
                        id = "selectedtab"
            )
        )
    )
))
