# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('despackage_timesTwo', PACKAGE = 'despackage', x)
}

desCpp <- function(params) {
    .Call('despackage_desCpp', PACKAGE = 'despackage', params)
}

