// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// desCpp
NumericMatrix desCpp(List transitions, IntegerMatrix transmat, NumericMatrix individual_attributes, NumericVector initial_times, NumericVector start_states, NumericVector tcovs);
RcppExport SEXP _multistateutils_desCpp(SEXP transitionsSEXP, SEXP transmatSEXP, SEXP individual_attributesSEXP, SEXP initial_timesSEXP, SEXP start_statesSEXP, SEXP tcovsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type transmat(transmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type individual_attributes(individual_attributesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_times(initial_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type start_states(start_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tcovs(tcovsSEXP);
    rcpp_result_gen = Rcpp::wrap(desCpp(transitions, transmat, individual_attributes, initial_times, start_states, tcovs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multistateutils_desCpp", (DL_FUNC) &_multistateutils_desCpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_multistateutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
